### PR TITLE
HOCS-2124 : add logging for failed members list retrieval

### PR DESCRIPTION
**Pull request by abarker66**
Add more detailed logging for investigation into members/refresh service failing on prod like environments.

### CODE REVIEW

**Comment by MarkWrightBjss** [comment]
If the process fails to get one of the lists, should it just log and then continue to the next list?

**Review by zuzak — APPROVED** [review]
Looks fine to me. Glad it logs which endpoint failed.

Ideally this would log the fields as several Json fields instead of one long concatenated string, but I don't know enough about Java exceptions to know if that's even possible.

**Comment by abarker66** [comment]
Yes it should but it does not. I raised a ticket to deal with this very issue - it is in the backlog. The service has a few vulnerabilities - missing endpoints, empty lists, etc all cause the service to fail.

**Comment by zuzak** [comment]
Yeah, I'm happy to merge this for now: it's an incremental improvement -- we should fix it properly, but for now it doesn't at all and we're not sure why.

**Comment by abarker66** [comment]
Good comments, I agree with them all, the service needs some rework but first I want to find out what is wrong with this issue in QA.

**Pull request merged**
